version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/main.json:/var/lib/grafana/dashboards/main.json
    networks:
      - monitoring
    depends_on:
      - prometheus

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - monitoring
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql



networks:
  monitoring: