version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/main.json:/var/lib/grafana/dashboards/main.json
    networks:
      - monitoring
    depends_on:
      - prometheus

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: order
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - monitoring
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init-scripts:/docker-entrypoint-initdb.d

  mysql-exporter:
    image: prom/mysqld-exporter
    ports:
      - "9104:9104"
    volumes:
      - ./mysql/my.cnf:/etc/my.cnf
    command:
      - "--config.my-cnf=/etc/my.cnf"
    environment:
      - DATA_SOURCE_NAME="root:admin@tcp(mysql:3306)/?allowCleartextPasswords=true"
      - FLAGS_COLLECT_INFO_SCHEMA_PROCESSLIST=true
      - FLAGS_COLLECT_INFO_SCHEMA_TABLES=true
    depends_on:
      - mysql
    networks:
      - monitoring

networks:
  monitoring: