{
 "title": "Order Service",
 "description": "Official Grafana dashboard for npm package @matteodisabatino/express-prometheus-middleware",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance:",
    "query": {
     "query": "label_values(nodejs_version_info, instance)"
    }
   },
   {
    "name": "node_exporter",
    "label": "Node Exporter:",
    "query": {
     "query": "label_values(node_uname_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Order X Payments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "total_number_of_orders", "legendFormat": "__auto" },
    { "expr": "total_number_of_payments", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Payments %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(total_number_of_payments / total_number_of_orders) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Business Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Service Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request duration average by request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{instance=\"$instance\"} / http_request_duration_seconds_count{instance=\"$instance\"}",
     "legendFormat": "{{method}} {{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Request count by request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_requests_total{instance=\"$instance\"}",
     "legendFormat": "{{method}} {{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "5xx by request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_requests_total{instance=\"$instance\",status=~\"5..\"}",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "4xx by request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_requests_total{instance=\"$instance\",status=~\"4..\"}",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Instance CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((sum(process_cpu_seconds_total{instance=\"$instance\"}) - avg(rate(node_cpu_seconds_total{instance=\"$node_exporter\",mode=\"idle\"}[$__rate_interval]))) * 100) / sum(node_cpu_seconds_total{instance=\"$node_exporter\"})",
     "legendFormat": "Usage CPU percentage by service"
    }
   ]
  },
  {
   "title": "Instance RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{instance=\"$instance\"}) / sum(node_memory_MemTotal_bytes{instance=\"$node_exporter\"}) * 100",
     "legendFormat": "Percentage of RAM used by service"
    }
   ]
  }
 ]
}